###############################################################################
# Makefile for the project DASCH_Plate_Cleaner_Rev2
###############################################################################

## General Flags
PROJECT = DASCH_Plate_Cleaner_Rev2
MCU = atmega1284p
TARGET = DASCH_Plate_Cleaner_Rev2.elf
CC = avr-c++

CPP = avr-g++

## Options common to compile, link and assembly rules
COMMON = -mmcu=$(MCU)

## Compile options common for all C compilation units.
CFLAGS = $(COMMON)
CFLAGS += -Wall -gdwarf-2 -Os -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums
CFLAGS += -MD -MP -MT $(*F).o -MF dep/$(@F).d 

## Assembly specific flags
ASMFLAGS = $(COMMON)
ASMFLAGS += $(CFLAGS)
ASMFLAGS += -x assembler-with-cpp -Wa,-gdwarf2

## Linker flags
LDFLAGS = $(COMMON)
LDFLAGS +=  -Wl,-Map=DASCH_Plate_Cleaner_Rev2.map


## Intel Hex file production flags
HEX_FLASH_FLAGS = -R .eeprom -R .fuse -R .lock -R .signature

HEX_EEPROM_FLAGS = -j .eeprom
HEX_EEPROM_FLAGS += --set-section-flags=.eeprom="alloc,load"
HEX_EEPROM_FLAGS += --change-section-lma .eeprom=0 --no-change-warnings


## Include Directories
INCLUDES = -I"C:\Users\Bob\Documents\DASH code\svndirectory\DASCH_Plate_Cleaner_Rev2\i2cmaster" -I"C:\Users\Bob\Documents\DASH code\svndirectory\DASCH_Plate_Cleaner_Rev2\." 

## Library Directories
LIBDIRS = -L"C:\libpololu-avr" 

## Libraries
LIBS = -lpololu_atmega1284p 

## Objects that must be built in order to link
OBJECTS = DASCH_Plate_Cleaner_Rev2.o twimaster.o 

## Objects explicitly added by the user
LINKONLYOBJECTS = 

## Build
all: $(TARGET) DASCH_Plate_Cleaner_Rev2.hex DASCH_Plate_Cleaner_Rev2.eep DASCH_Plate_Cleaner_Rev2.lss## Compile
DASCH_Plate_Cleaner_Rev2.o: ../DASCH_Plate_Cleaner_Rev2.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

twimaster.o: ../i2cmaster/twimaster.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

##Link
$(TARGET): $(OBJECTS)
	 $(CC) $(LDFLAGS) $(OBJECTS) $(LINKONLYOBJECTS) $(LIBDIRS) $(LIBS) -o $(TARGET)

%.hex: $(TARGET)
	avr-objcopy -O ihex $(HEX_FLASH_FLAGS)  $< $@

%.eep: $(TARGET)
	-avr-objcopy $(HEX_EEPROM_FLAGS) -O ihex $< $@ || exit 0

%.lss: $(TARGET)
	avr-objdump -h -S $< > $@

## Clean target
.PHONY: clean
clean:
	-rm -rf $(OBJECTS) DASCH_Plate_Cleaner_Rev2.elf dep/* DASCH_Plate_Cleaner_Rev2.hex DASCH_Plate_Cleaner_Rev2.eep DASCH_Plate_Cleaner_Rev2.lss DASCH_Plate_Cleaner_Rev2.map


## Other dependencies
-include $(shell mkdir dep 2>NUL) $(wildcard dep/*)

